// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	language "golang.org/x/text/language"

	translate "cloud.google.com/go/translate"
)

// MockGoogleClient is an autogenerated mock type for the GoogleClient type
type MockGoogleClient struct {
	mock.Mock
}

type MockGoogleClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoogleClient) EXPECT() *MockGoogleClient_Expecter {
	return &MockGoogleClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockGoogleClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoogleClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockGoogleClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockGoogleClient_Expecter) Close() *MockGoogleClient_Close_Call {
	return &MockGoogleClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockGoogleClient_Close_Call) Run(run func()) *MockGoogleClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGoogleClient_Close_Call) Return(_a0 error) *MockGoogleClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoogleClient_Close_Call) RunAndReturn(run func() error) *MockGoogleClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Translate provides a mock function with given fields: ctx, src, target, opts
func (_m *MockGoogleClient) Translate(ctx context.Context, src []string, target language.Tag, opts *translate.Options) ([]translate.Translation, error) {
	ret := _m.Called(ctx, src, target, opts)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 []translate.Translation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, language.Tag, *translate.Options) ([]translate.Translation, error)); ok {
		return rf(ctx, src, target, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, language.Tag, *translate.Options) []translate.Translation); ok {
		r0 = rf(ctx, src, target, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]translate.Translation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, language.Tag, *translate.Options) error); ok {
		r1 = rf(ctx, src, target, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoogleClient_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockGoogleClient_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - ctx context.Context
//   - src []string
//   - target language.Tag
//   - opts *translate.Options
func (_e *MockGoogleClient_Expecter) Translate(ctx interface{}, src interface{}, target interface{}, opts interface{}) *MockGoogleClient_Translate_Call {
	return &MockGoogleClient_Translate_Call{Call: _e.mock.On("Translate", ctx, src, target, opts)}
}

func (_c *MockGoogleClient_Translate_Call) Run(run func(ctx context.Context, src []string, target language.Tag, opts *translate.Options)) *MockGoogleClient_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(language.Tag), args[3].(*translate.Options))
	})
	return _c
}

func (_c *MockGoogleClient_Translate_Call) Return(_a0 []translate.Translation, _a1 error) *MockGoogleClient_Translate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoogleClient_Translate_Call) RunAndReturn(run func(context.Context, []string, language.Tag, *translate.Options) ([]translate.Translation, error)) *MockGoogleClient_Translate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoogleClient creates a new instance of MockGoogleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoogleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoogleClient {
	mock := &MockGoogleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
