# file: .golangci.yml
# version: 1.2.0
# guid: 4d5e6f7a-8b9c-0123-def4-56789abcdef0

# Modern GolangCI-Lint configuration
# https://golangci-lint.run/docs/configuration/

version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: "1.24"
  build-tags:
    - sqlite
    - gcommonmetrics

linters:
  enable:
    # Essential linters for Go code quality
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    - revive
    - gocyclo
    - funlen
    - gosec
    - goconst
    - misspell
    - unconvert
    - unparam
    - lll
    - bodyclose
    - noctx
    - rowserrcheck
    - gocritic

  disable:
    # Disable overly opinionated linters
    - varnamelen
    - testpackage
    - paralleltest
    - gochecknoglobals
    - gochecknoinits

formatters:
  enable:
    - gofmt
    - goimports
