# file: .mockery.yaml
# Mockery configuration file to address deprecation warnings
# Migration from command-line args to packages configuration

with-expecter: true
issue-845-fix: true
resolve-type-alias: false
disable-version-string: true
