// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEncryption creates a new instance of MockEncryption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncryption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncryption {
	mock := &MockEncryption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEncryption is an autogenerated mock type for the Encryption type
type MockEncryption struct {
	mock.Mock
}

type MockEncryption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncryption) EXPECT() *MockEncryption_Expecter {
	return &MockEncryption_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockEncryption
func (_mock *MockEncryption) Decrypt(data []byte) ([]byte, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncryption_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockEncryption_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - data []byte
func (_e *MockEncryption_Expecter) Decrypt(data interface{}) *MockEncryption_Decrypt_Call {
	return &MockEncryption_Decrypt_Call{Call: _e.mock.On("Decrypt", data)}
}

func (_c *MockEncryption_Decrypt_Call) Run(run func(data []byte)) *MockEncryption_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEncryption_Decrypt_Call) Return(bytes []byte, err error) *MockEncryption_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockEncryption_Decrypt_Call) RunAndReturn(run func(data []byte) ([]byte, error)) *MockEncryption_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockEncryption
func (_mock *MockEncryption) Encrypt(data []byte) ([]byte, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncryption_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockEncryption_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - data []byte
func (_e *MockEncryption_Expecter) Encrypt(data interface{}) *MockEncryption_Encrypt_Call {
	return &MockEncryption_Encrypt_Call{Call: _e.mock.On("Encrypt", data)}
}

func (_c *MockEncryption_Encrypt_Call) Run(run func(data []byte)) *MockEncryption_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEncryption_Encrypt_Call) Return(bytes []byte, err error) *MockEncryption_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockEncryption_Encrypt_Call) RunAndReturn(run func(data []byte) ([]byte, error)) *MockEncryption_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
