// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockProvider
func (_mock *MockProvider) Fetch(ctx context.Context, mediaPath string, lang string) ([]byte, error) {
	ret := _mock.Called(ctx, mediaPath, lang)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return returnFunc(ctx, mediaPath, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = returnFunc(ctx, mediaPath, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, mediaPath, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockProvider_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaPath string
//   - lang string
func (_e *MockProvider_Expecter) Fetch(ctx interface{}, mediaPath interface{}, lang interface{}) *MockProvider_Fetch_Call {
	return &MockProvider_Fetch_Call{Call: _e.mock.On("Fetch", ctx, mediaPath, lang)}
}

func (_c *MockProvider_Fetch_Call) Run(run func(ctx context.Context, mediaPath string, lang string)) *MockProvider_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_Fetch_Call) Return(bytes []byte, err error) *MockProvider_Fetch_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProvider_Fetch_Call) RunAndReturn(run func(ctx context.Context, mediaPath string, lang string) ([]byte, error)) *MockProvider_Fetch_Call {
	_c.Call.Return(run)
	return _c
}
