// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSearcher creates a new instance of MockSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearcher {
	mock := &MockSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearcher is an autogenerated mock type for the Searcher type
type MockSearcher struct {
	mock.Mock
}

type MockSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearcher) EXPECT() *MockSearcher_Expecter {
	return &MockSearcher_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type MockSearcher
func (_mock *MockSearcher) Search(ctx context.Context, mediaPath string, lang string) ([]string, error) {
	ret := _mock.Called(ctx, mediaPath, lang)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, mediaPath, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, mediaPath, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, mediaPath, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearcher_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSearcher_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaPath string
//   - lang string
func (_e *MockSearcher_Expecter) Search(ctx interface{}, mediaPath interface{}, lang interface{}) *MockSearcher_Search_Call {
	return &MockSearcher_Search_Call{Call: _e.mock.On("Search", ctx, mediaPath, lang)}
}

func (_c *MockSearcher_Search_Call) Run(run func(ctx context.Context, mediaPath string, lang string)) *MockSearcher_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSearcher_Search_Call) Return(strings []string, err error) *MockSearcher_Search_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSearcher_Search_Call) RunAndReturn(run func(ctx context.Context, mediaPath string, lang string) ([]string, error)) *MockSearcher_Search_Call {
	_c.Call.Return(run)
	return _c
}
