// file: proto/queue_job.proto
// version: 1.0.0
// guid: 1f3aeed2-6b5a-4e2c-bc6c-123456789abc

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: queue_job.proto

package jobpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TranslationJob represents a translation request for one or more subtitle files.
type TranslationJob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Paths to subtitle files to translate. Use one entry for single-file jobs.
	InputPaths []string `protobuf:"bytes,1,rep,name=input_paths,json=inputPaths,proto3" json:"input_paths,omitempty"`
	// Destination path for the output subtitle file when translating a single file.
	OutputPath string `protobuf:"bytes,2,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	// Target language code, e.g. "en" or "es".
	Language string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	// Translation service identifier (google, gpt, grpc).
	Service string `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	// API key for Google Translate when using the google service.
	GoogleKey string `protobuf:"bytes,5,opt,name=google_key,json=googleKey,proto3" json:"google_key,omitempty"`
	// API key for OpenAI when using the gpt service.
	GptKey string `protobuf:"bytes,6,opt,name=gpt_key,json=gptKey,proto3" json:"gpt_key,omitempty"`
	// Address of a remote gRPC translator service.
	GrpcAddr string `protobuf:"bytes,7,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	// Number of workers for batch translation.
	Workers       int32 `protobuf:"varint,8,opt,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationJob) Reset() {
	*x = TranslationJob{}
	mi := &file_queue_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationJob) ProtoMessage() {}

func (x *TranslationJob) ProtoReflect() protoreflect.Message {
	mi := &file_queue_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationJob.ProtoReflect.Descriptor instead.
func (*TranslationJob) Descriptor() ([]byte, []int) {
	return file_queue_job_proto_rawDescGZIP(), []int{0}
}

func (x *TranslationJob) GetInputPaths() []string {
	if x != nil {
		return x.InputPaths
	}
	return nil
}

func (x *TranslationJob) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *TranslationJob) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranslationJob) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TranslationJob) GetGoogleKey() string {
	if x != nil {
		return x.GoogleKey
	}
	return ""
}

func (x *TranslationJob) GetGptKey() string {
	if x != nil {
		return x.GptKey
	}
	return ""
}

func (x *TranslationJob) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *TranslationJob) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

var File_queue_job_proto protoreflect.FileDescriptor

const file_queue_job_proto_rawDesc = "" +
	"\n" +
	"\x0fqueue_job.proto\x12\vsubtitle.v1\"\xf7\x01\n" +
	"\x0eTranslationJob\x12\x1f\n" +
	"\vinput_paths\x18\x01 \x03(\tR\n" +
	"inputPaths\x12\x1f\n" +
	"\voutput_path\x18\x02 \x01(\tR\n" +
	"outputPath\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"google_key\x18\x05 \x01(\tR\tgoogleKey\x12\x17\n" +
	"\agpt_key\x18\x06 \x01(\tR\x06gptKey\x12\x1b\n" +
	"\tgrpc_addr\x18\a \x01(\tR\bgrpcAddr\x12\x18\n" +
	"\aworkers\x18\b \x01(\x05R\aworkersB.Z,github.com/jdfalk/subtitle-manager/pkg/jobpbb\x06proto3"

var (
	file_queue_job_proto_rawDescOnce sync.Once
	file_queue_job_proto_rawDescData []byte
)

func file_queue_job_proto_rawDescGZIP() []byte {
	file_queue_job_proto_rawDescOnce.Do(func() {
		file_queue_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_queue_job_proto_rawDesc), len(file_queue_job_proto_rawDesc)))
	})
	return file_queue_job_proto_rawDescData
}

var file_queue_job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_queue_job_proto_goTypes = []any{
	(*TranslationJob)(nil), // 0: subtitle.v1.TranslationJob
}
var file_queue_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_queue_job_proto_init() }
func file_queue_job_proto_init() {
	if File_queue_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_job_proto_rawDesc), len(file_queue_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queue_job_proto_goTypes,
		DependencyIndexes: file_queue_job_proto_depIdxs,
		MessageInfos:      file_queue_job_proto_msgTypes,
	}.Build()
	File_queue_job_proto = out.File
	file_queue_job_proto_goTypes = nil
	file_queue_job_proto_depIdxs = nil
}
