# file: .github/ISSUE_TEMPLATE/bug_report.yml
# version: 1.0.0
# guid: a1b2c3d4-e5f6-7890-abcd-ef1234567890

name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      value: |
        - OS: [e.g. Windows 10, macOS 13.1, Ubuntu 22.04]
        - Subtitle Manager Version: [e.g. v1.0.0]
        - Go Version: [e.g. 1.21.0]
        - Deployment Method: [e.g. Docker, Binary, Source]
        - Browser (if web UI related): [e.g. Chrome 120, Firefox 121]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any relevant log output. Please wrap logs in code blocks.
      placeholder: |
        ```
        Paste your logs here...
        ```

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration settings (remove sensitive information)
      placeholder: |
        ```yaml
        # Paste relevant config here...
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Screenshots, related issues, workarounds, etc.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I have removed or obscured any sensitive information from logs/config
          required: true
