# file: .github/ISSUE_TEMPLATE/config.yml
# version: 1.0.0
# guid: d4e5f6g7-h8i9-0123-defg-456789012345

blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/jdfalk/subtitle-manager/blob/main/README.md
    about: Read the documentation for setup and usage instructions
  - name: 💬 Discussions
    url: https://github.com/jdfalk/subtitle-manager/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🚀 Enhancement Guide
    url: https://github.com/jdfalk/subtitle-manager/blob/main/docs/ISSUE_ENHANCEMENT_GUIDE.md
    about: Guide for creating detailed enhancement requests for junior developers
