extends:
  - eslint:recommended
  - "@typescript-eslint/recommended"
  - google

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

env:
  browser: true
  es2021: true
  node: true
  jest: true

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  max-len:
    - error
    - code: 80
      ignoreUrls: true
  no-console: warn
  no-unused-vars: error
  no-var: error
  prefer-const: error
  eqeqeq: error
  no-trailing-spaces: error
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  object-curly-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - never
  computed-property-spacing:
    - error
    - never
  func-call-spacing:
    - error
    - never
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  keyword-spacing:
    - error
    - before: true
      after: true
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  spaced-comment:
    - error
    - always
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/no-explicit-any": warn
