// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: subtitle/job/v1/queue_job.proto

//go:build protoopaque

package jobpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TranslationJob represents a translation request for one or more subtitle files.
type TranslationJob struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InputPaths  []string               `protobuf:"bytes,1,rep,name=input_paths,json=inputPaths"`
	xxx_hidden_OutputPath  *string                `protobuf:"bytes,2,opt,name=output_path,json=outputPath"`
	xxx_hidden_Language    *string                `protobuf:"bytes,3,opt,name=language"`
	xxx_hidden_Service     *string                `protobuf:"bytes,4,opt,name=service"`
	xxx_hidden_GoogleKey   *string                `protobuf:"bytes,5,opt,name=google_key,json=googleKey"`
	xxx_hidden_GptKey      *string                `protobuf:"bytes,6,opt,name=gpt_key,json=gptKey"`
	xxx_hidden_GrpcAddr    *string                `protobuf:"bytes,7,opt,name=grpc_addr,json=grpcAddr"`
	xxx_hidden_Workers     int32                  `protobuf:"varint,8,opt,name=workers"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TranslationJob) Reset() {
	*x = TranslationJob{}
	mi := &file_subtitle_job_v1_queue_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationJob) ProtoMessage() {}

func (x *TranslationJob) ProtoReflect() protoreflect.Message {
	mi := &file_subtitle_job_v1_queue_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TranslationJob) GetInputPaths() []string {
	if x != nil {
		return x.xxx_hidden_InputPaths
	}
	return nil
}

func (x *TranslationJob) GetOutputPath() string {
	if x != nil {
		if x.xxx_hidden_OutputPath != nil {
			return *x.xxx_hidden_OutputPath
		}
		return ""
	}
	return ""
}

func (x *TranslationJob) GetLanguage() string {
	if x != nil {
		if x.xxx_hidden_Language != nil {
			return *x.xxx_hidden_Language
		}
		return ""
	}
	return ""
}

func (x *TranslationJob) GetService() string {
	if x != nil {
		if x.xxx_hidden_Service != nil {
			return *x.xxx_hidden_Service
		}
		return ""
	}
	return ""
}

func (x *TranslationJob) GetGoogleKey() string {
	if x != nil {
		if x.xxx_hidden_GoogleKey != nil {
			return *x.xxx_hidden_GoogleKey
		}
		return ""
	}
	return ""
}

func (x *TranslationJob) GetGptKey() string {
	if x != nil {
		if x.xxx_hidden_GptKey != nil {
			return *x.xxx_hidden_GptKey
		}
		return ""
	}
	return ""
}

func (x *TranslationJob) GetGrpcAddr() string {
	if x != nil {
		if x.xxx_hidden_GrpcAddr != nil {
			return *x.xxx_hidden_GrpcAddr
		}
		return ""
	}
	return ""
}

func (x *TranslationJob) GetWorkers() int32 {
	if x != nil {
		return x.xxx_hidden_Workers
	}
	return 0
}

func (x *TranslationJob) SetInputPaths(v []string) {
	x.xxx_hidden_InputPaths = v
}

func (x *TranslationJob) SetOutputPath(v string) {
	x.xxx_hidden_OutputPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *TranslationJob) SetLanguage(v string) {
	x.xxx_hidden_Language = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *TranslationJob) SetService(v string) {
	x.xxx_hidden_Service = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *TranslationJob) SetGoogleKey(v string) {
	x.xxx_hidden_GoogleKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *TranslationJob) SetGptKey(v string) {
	x.xxx_hidden_GptKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *TranslationJob) SetGrpcAddr(v string) {
	x.xxx_hidden_GrpcAddr = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *TranslationJob) SetWorkers(v int32) {
	x.xxx_hidden_Workers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *TranslationJob) HasOutputPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TranslationJob) HasLanguage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TranslationJob) HasService() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TranslationJob) HasGoogleKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TranslationJob) HasGptKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *TranslationJob) HasGrpcAddr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *TranslationJob) HasWorkers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *TranslationJob) ClearOutputPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OutputPath = nil
}

func (x *TranslationJob) ClearLanguage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Language = nil
}

func (x *TranslationJob) ClearService() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Service = nil
}

func (x *TranslationJob) ClearGoogleKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_GoogleKey = nil
}

func (x *TranslationJob) ClearGptKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_GptKey = nil
}

func (x *TranslationJob) ClearGrpcAddr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_GrpcAddr = nil
}

func (x *TranslationJob) ClearWorkers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Workers = 0
}

type TranslationJob_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Paths to subtitle files to translate. Use one entry for single-file jobs.
	InputPaths []string
	// Destination path for the output subtitle file when translating a single file.
	OutputPath *string
	// Target language code, e.g. "en" or "es".
	Language *string
	// Translation service identifier (google, gpt, grpc).
	Service *string
	// API key for Google Translate when using the google service.
	GoogleKey *string
	// API key for OpenAI when using the gpt service.
	GptKey *string
	// Address of a remote gRPC translator service.
	GrpcAddr *string
	// Number of workers for batch translation.
	Workers *int32
}

func (b0 TranslationJob_builder) Build() *TranslationJob {
	m0 := &TranslationJob{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InputPaths = b.InputPaths
	if b.OutputPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_OutputPath = b.OutputPath
	}
	if b.Language != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Language = b.Language
	}
	if b.Service != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Service = b.Service
	}
	if b.GoogleKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_GoogleKey = b.GoogleKey
	}
	if b.GptKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_GptKey = b.GptKey
	}
	if b.GrpcAddr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_GrpcAddr = b.GrpcAddr
	}
	if b.Workers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_Workers = *b.Workers
	}
	return m0
}

var File_subtitle_job_v1_queue_job_proto protoreflect.FileDescriptor

const file_subtitle_job_v1_queue_job_proto_rawDesc = "" +
	"\n" +
	"\x1fsubtitle/job/v1/queue_job.proto\x12\x0fsubtitle.job.v1\x1a!google/protobuf/go_features.proto\"\xf7\x01\n" +
	"\x0eTranslationJob\x12\x1f\n" +
	"\vinput_paths\x18\x01 \x03(\tR\n" +
	"inputPaths\x12\x1f\n" +
	"\voutput_path\x18\x02 \x01(\tR\n" +
	"outputPath\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"google_key\x18\x05 \x01(\tR\tgoogleKey\x12\x17\n" +
	"\agpt_key\x18\x06 \x01(\tR\x06gptKey\x12\x1b\n" +
	"\tgrpc_addr\x18\a \x01(\tR\bgrpcAddr\x12\x18\n" +
	"\aworkers\x18\b \x01(\x05R\aworkersB<Z2github.com/jdfalk/subtitle-manager/pkg/jobpb;jobpb\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_subtitle_job_v1_queue_job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_subtitle_job_v1_queue_job_proto_goTypes = []any{
	(*TranslationJob)(nil), // 0: subtitle.job.v1.TranslationJob
}
var file_subtitle_job_v1_queue_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subtitle_job_v1_queue_job_proto_init() }
func file_subtitle_job_v1_queue_job_proto_init() {
	if File_subtitle_job_v1_queue_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subtitle_job_v1_queue_job_proto_rawDesc), len(file_subtitle_job_v1_queue_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subtitle_job_v1_queue_job_proto_goTypes,
		DependencyIndexes: file_subtitle_job_v1_queue_job_proto_depIdxs,
		MessageInfos:      file_subtitle_job_v1_queue_job_proto_msgTypes,
	}.Build()
	File_subtitle_job_v1_queue_job_proto = out.File
	file_subtitle_job_v1_queue_job_proto_goTypes = nil
	file_subtitle_job_v1_queue_job_proto_depIdxs = nil
}
