// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: translator.proto

// file: proto/translator.proto
// version: 1.1.0
// guid: 70eca88d-31fe-4044-8b76-a22bd3c9e0bd

//go:build !protoopaque

package translatorpb

import (
	proto "github.com/jdfalk/gcommon/pkg/common/proto/messages"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslateRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Meta          *proto.RequestMetadata `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Text          *string                `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Language      *string                `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_translator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TranslateRequest) GetMeta() *proto.RequestMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TranslateRequest) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *TranslateRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *TranslateRequest) SetMeta(v *proto.RequestMetadata) {
	x.Meta = v
}

func (x *TranslateRequest) SetText(v string) {
	x.Text = &v
}

func (x *TranslateRequest) SetLanguage(v string) {
	x.Language = &v
}

func (x *TranslateRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return x.Meta != nil
}

func (x *TranslateRequest) HasText() bool {
	if x == nil {
		return false
	}
	return x.Text != nil
}

func (x *TranslateRequest) HasLanguage() bool {
	if x == nil {
		return false
	}
	return x.Language != nil
}

func (x *TranslateRequest) ClearMeta() {
	x.Meta = nil
}

func (x *TranslateRequest) ClearText() {
	x.Text = nil
}

func (x *TranslateRequest) ClearLanguage() {
	x.Language = nil
}

type TranslateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Meta     *proto.RequestMetadata
	Text     *string
	Language *string
}

func (b0 TranslateRequest_builder) Build() *TranslateRequest {
	m0 := &TranslateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Meta = b.Meta
	x.Text = b.Text
	x.Language = b.Language
	return m0
}

type TranslateResponse struct {
	state          protoimpl.MessageState `protogen:"hybrid.v1"`
	TranslatedText *string                `protobuf:"bytes,1,opt,name=translated_text,json=translatedText" json:"translated_text,omitempty"`
	Errors         []*proto.Error         `protobuf:"bytes,2,rep,name=errors" json:"errors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_translator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TranslateResponse) GetTranslatedText() string {
	if x != nil && x.TranslatedText != nil {
		return *x.TranslatedText
	}
	return ""
}

func (x *TranslateResponse) GetErrors() []*proto.Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *TranslateResponse) SetTranslatedText(v string) {
	x.TranslatedText = &v
}

func (x *TranslateResponse) SetErrors(v []*proto.Error) {
	x.Errors = v
}

func (x *TranslateResponse) HasTranslatedText() bool {
	if x == nil {
		return false
	}
	return x.TranslatedText != nil
}

func (x *TranslateResponse) ClearTranslatedText() {
	x.TranslatedText = nil
}

type TranslateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TranslatedText *string
	Errors         []*proto.Error
}

func (b0 TranslateResponse_builder) Build() *TranslateResponse {
	m0 := &TranslateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.TranslatedText = b.TranslatedText
	x.Errors = b.Errors
	return m0
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Settings      map[string]string      `protobuf:"bytes,1,rep,name=settings" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_translator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigResponse) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ConfigResponse) SetSettings(v map[string]string) {
	x.Settings = v
}

type ConfigResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Settings map[string]string
}

func (b0 ConfigResponse_builder) Build() *ConfigResponse {
	m0 := &ConfigResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Settings = b.Settings
	return m0
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Meta          *proto.RequestMetadata `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Settings      map[string]string      `protobuf:"bytes,2,rep,name=settings" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_translator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigRequest) GetMeta() *proto.RequestMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ConfigRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ConfigRequest) SetMeta(v *proto.RequestMetadata) {
	x.Meta = v
}

func (x *ConfigRequest) SetSettings(v map[string]string) {
	x.Settings = v
}

func (x *ConfigRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return x.Meta != nil
}

func (x *ConfigRequest) ClearMeta() {
	x.Meta = nil
}

type ConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Meta     *proto.RequestMetadata
	Settings map[string]string
}

func (b0 ConfigRequest_builder) Build() *ConfigRequest {
	m0 := &ConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Meta = b.Meta
	x.Settings = b.Settings
	return m0
}

var File_translator_proto protoreflect.FileDescriptor

const file_translator_proto_rawDesc = "" +
	"\n" +
	"\x10translator.proto\x12\x15gcommon.v1.translator\x1a!google/protobuf/go_features.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a0pkg/common/proto/messages/request_metadata.proto\x1a%pkg/common/proto/messages/error.proto\"z\n" +
	"\x10TranslateRequest\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".gcommon.v1.common.RequestMetadataR\x04meta\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"n\n" +
	"\x11TranslateResponse\x12'\n" +
	"\x0ftranslated_text\x18\x01 \x01(\tR\x0etranslatedText\x120\n" +
	"\x06errors\x18\x02 \x03(\v2\x18.gcommon.v1.common.ErrorR\x06errors\"\x9e\x01\n" +
	"\x0eConfigResponse\x12O\n" +
	"\bsettings\x18\x01 \x03(\v23.gcommon.v1.translator.ConfigResponse.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\rConfigRequest\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".gcommon.v1.common.RequestMetadataR\x04meta\x12N\n" +
	"\bsettings\x18\x02 \x03(\v22.gcommon.v1.translator.ConfigRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8a\x02\n" +
	"\x11TranslatorService\x12^\n" +
	"\tTranslate\x12'.gcommon.v1.translator.TranslateRequest\x1a(.gcommon.v1.translator.TranslateResponse\x12J\n" +
	"\tGetConfig\x12\x16.google.protobuf.Empty\x1a%.gcommon.v1.translator.ConfigResponse\x12I\n" +
	"\tSetConfig\x12$.gcommon.v1.translator.ConfigRequest\x1a\x16.google.protobuf.EmptyBJZ@github.com/jdfalk/subtitle-manager/pkg/translatorpb;translatorpb\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_translator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_translator_proto_goTypes = []any{
	(*TranslateRequest)(nil),      // 0: gcommon.v1.translator.TranslateRequest
	(*TranslateResponse)(nil),     // 1: gcommon.v1.translator.TranslateResponse
	(*ConfigResponse)(nil),        // 2: gcommon.v1.translator.ConfigResponse
	(*ConfigRequest)(nil),         // 3: gcommon.v1.translator.ConfigRequest
	nil,                           // 4: gcommon.v1.translator.ConfigResponse.SettingsEntry
	nil,                           // 5: gcommon.v1.translator.ConfigRequest.SettingsEntry
	(*proto.RequestMetadata)(nil), // 6: gcommon.v1.common.RequestMetadata
	(*proto.Error)(nil),           // 7: gcommon.v1.common.Error
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_translator_proto_depIdxs = []int32{
	6, // 0: gcommon.v1.translator.TranslateRequest.meta:type_name -> gcommon.v1.common.RequestMetadata
	7, // 1: gcommon.v1.translator.TranslateResponse.errors:type_name -> gcommon.v1.common.Error
	4, // 2: gcommon.v1.translator.ConfigResponse.settings:type_name -> gcommon.v1.translator.ConfigResponse.SettingsEntry
	6, // 3: gcommon.v1.translator.ConfigRequest.meta:type_name -> gcommon.v1.common.RequestMetadata
	5, // 4: gcommon.v1.translator.ConfigRequest.settings:type_name -> gcommon.v1.translator.ConfigRequest.SettingsEntry
	0, // 5: gcommon.v1.translator.TranslatorService.Translate:input_type -> gcommon.v1.translator.TranslateRequest
	8, // 6: gcommon.v1.translator.TranslatorService.GetConfig:input_type -> google.protobuf.Empty
	3, // 7: gcommon.v1.translator.TranslatorService.SetConfig:input_type -> gcommon.v1.translator.ConfigRequest
	1, // 8: gcommon.v1.translator.TranslatorService.Translate:output_type -> gcommon.v1.translator.TranslateResponse
	2, // 9: gcommon.v1.translator.TranslatorService.GetConfig:output_type -> gcommon.v1.translator.ConfigResponse
	8, // 10: gcommon.v1.translator.TranslatorService.SetConfig:output_type -> google.protobuf.Empty
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_translator_proto_init() }
func file_translator_proto_init() {
	if File_translator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translator_proto_rawDesc), len(file_translator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translator_proto_goTypes,
		DependencyIndexes: file_translator_proto_depIdxs,
		MessageInfos:      file_translator_proto_msgTypes,
	}.Build()
	File_translator_proto = out.File
	file_translator_proto_goTypes = nil
	file_translator_proto_depIdxs = nil
}
