// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: translator.proto

//go:build protoopaque

package translatorpb

import (
	configpb "github.com/jdfalk/subtitle-manager/pkg/configpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Temporary local types until gcommon is properly integrated
type RequestMetadata struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RequestId   *string                `protobuf:"bytes,1,opt,name=request_id,json=requestId"`
	xxx_hidden_UserId      *string                `protobuf:"bytes,2,opt,name=user_id,json=userId"`
	xxx_hidden_Headers     map[string]string      `protobuf:"bytes,3,rep,name=headers" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_translator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RequestMetadata) GetRequestId() string {
	if x != nil {
		if x.xxx_hidden_RequestId != nil {
			return *x.xxx_hidden_RequestId
		}
		return ""
	}
	return ""
}

func (x *RequestMetadata) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *RequestMetadata) GetHeaders() map[string]string {
	if x != nil {
		return x.xxx_hidden_Headers
	}
	return nil
}

func (x *RequestMetadata) SetRequestId(v string) {
	x.xxx_hidden_RequestId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RequestMetadata) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RequestMetadata) SetHeaders(v map[string]string) {
	x.xxx_hidden_Headers = v
}

func (x *RequestMetadata) HasRequestId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RequestMetadata) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RequestMetadata) ClearRequestId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RequestId = nil
}

func (x *RequestMetadata) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UserId = nil
}

type RequestMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RequestId *string
	UserId    *string
	Headers   map[string]string
}

func (b0 RequestMetadata_builder) Build() *RequestMetadata {
	m0 := &RequestMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RequestId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RequestId = b.RequestId
	}
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_UserId = b.UserId
	}
	x.xxx_hidden_Headers = b.Headers
	return m0
}

type Error struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Code        *string                `protobuf:"bytes,1,opt,name=code"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	xxx_hidden_Details     *string                `protobuf:"bytes,3,opt,name=details"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_translator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Error) GetCode() string {
	if x != nil {
		if x.xxx_hidden_Code != nil {
			return *x.xxx_hidden_Code
		}
		return ""
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *Error) GetDetails() string {
	if x != nil {
		if x.xxx_hidden_Details != nil {
			return *x.xxx_hidden_Details
		}
		return ""
	}
	return ""
}

func (x *Error) SetCode(v string) {
	x.xxx_hidden_Code = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Error) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Error) SetDetails(v string) {
	x.xxx_hidden_Details = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Error) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Error) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Error) HasDetails() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Error) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Code = nil
}

func (x *Error) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

func (x *Error) ClearDetails() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Details = nil
}

type Error_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Code    *string
	Message *string
	Details *string
}

func (b0 Error_builder) Build() *Error {
	m0 := &Error{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Code = b.Code
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Message = b.Message
	}
	if b.Details != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Details = b.Details
	}
	return m0
}

type TranslateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Meta        *RequestMetadata       `protobuf:"bytes,1,opt,name=meta"`
	xxx_hidden_Text        *string                `protobuf:"bytes,2,opt,name=text"`
	xxx_hidden_Language    *string                `protobuf:"bytes,3,opt,name=language"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_translator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TranslateRequest) GetMeta() *RequestMetadata {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *TranslateRequest) GetText() string {
	if x != nil {
		if x.xxx_hidden_Text != nil {
			return *x.xxx_hidden_Text
		}
		return ""
	}
	return ""
}

func (x *TranslateRequest) GetLanguage() string {
	if x != nil {
		if x.xxx_hidden_Language != nil {
			return *x.xxx_hidden_Language
		}
		return ""
	}
	return ""
}

func (x *TranslateRequest) SetMeta(v *RequestMetadata) {
	x.xxx_hidden_Meta = v
}

func (x *TranslateRequest) SetText(v string) {
	x.xxx_hidden_Text = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *TranslateRequest) SetLanguage(v string) {
	x.xxx_hidden_Language = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *TranslateRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Meta != nil
}

func (x *TranslateRequest) HasText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TranslateRequest) HasLanguage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TranslateRequest) ClearMeta() {
	x.xxx_hidden_Meta = nil
}

func (x *TranslateRequest) ClearText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Text = nil
}

func (x *TranslateRequest) ClearLanguage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Language = nil
}

type TranslateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Meta     *RequestMetadata
	Text     *string
	Language *string
}

func (b0 TranslateRequest_builder) Build() *TranslateRequest {
	m0 := &TranslateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Meta = b.Meta
	if b.Text != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Text = b.Text
	}
	if b.Language != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Language = b.Language
	}
	return m0
}

type TranslateResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TranslatedText *string                `protobuf:"bytes,1,opt,name=translated_text,json=translatedText"`
	xxx_hidden_Errors         *[]*Error              `protobuf:"bytes,2,rep,name=errors"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_translator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TranslateResponse) GetTranslatedText() string {
	if x != nil {
		if x.xxx_hidden_TranslatedText != nil {
			return *x.xxx_hidden_TranslatedText
		}
		return ""
	}
	return ""
}

func (x *TranslateResponse) GetErrors() []*Error {
	if x != nil {
		if x.xxx_hidden_Errors != nil {
			return *x.xxx_hidden_Errors
		}
	}
	return nil
}

func (x *TranslateResponse) SetTranslatedText(v string) {
	x.xxx_hidden_TranslatedText = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *TranslateResponse) SetErrors(v []*Error) {
	x.xxx_hidden_Errors = &v
}

func (x *TranslateResponse) HasTranslatedText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TranslateResponse) ClearTranslatedText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TranslatedText = nil
}

type TranslateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TranslatedText *string
	Errors         []*Error
}

func (b0 TranslateResponse_builder) Build() *TranslateResponse {
	m0 := &TranslateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TranslatedText != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_TranslatedText = b.TranslatedText
	}
	x.xxx_hidden_Errors = &b.Errors
	return m0
}

// Standard request/response wrappers for config operations
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_translator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetConfigRequest_builder) Build() *GetConfigRequest {
	m0 := &GetConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetConfigResponse struct {
	state             protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Config *configpb.SubtitleManagerConfig `protobuf:"bytes,1,opt,name=config"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_translator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetConfigResponse) GetConfig() *configpb.SubtitleManagerConfig {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *GetConfigResponse) SetConfig(v *configpb.SubtitleManagerConfig) {
	x.xxx_hidden_Config = v
}

func (x *GetConfigResponse) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *GetConfigResponse) ClearConfig() {
	x.xxx_hidden_Config = nil
}

type GetConfigResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Config *configpb.SubtitleManagerConfig
}

func (b0 GetConfigResponse_builder) Build() *GetConfigResponse {
	m0 := &GetConfigResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Config = b.Config
	return m0
}

type SetConfigRequest struct {
	state             protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Config *configpb.SubtitleManagerConfig `protobuf:"bytes,1,opt,name=config"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_translator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetConfigRequest) GetConfig() *configpb.SubtitleManagerConfig {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *SetConfigRequest) SetConfig(v *configpb.SubtitleManagerConfig) {
	x.xxx_hidden_Config = v
}

func (x *SetConfigRequest) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *SetConfigRequest) ClearConfig() {
	x.xxx_hidden_Config = nil
}

type SetConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Config *configpb.SubtitleManagerConfig
}

func (b0 SetConfigRequest_builder) Build() *SetConfigRequest {
	m0 := &SetConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Config = b.Config
	return m0
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_translator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetConfigResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetConfigResponse_builder) Build() *SetConfigResponse {
	m0 := &SetConfigResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// RateLimit defines basic provider rate limiting parameters.
type RateLimit struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RequestsPerMinute uint32                 `protobuf:"varint,1,opt,name=requests_per_minute,json=requestsPerMinute"`
	xxx_hidden_Burst             uint32                 `protobuf:"varint,2,opt,name=burst"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_translator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RateLimit) GetRequestsPerMinute() uint32 {
	if x != nil {
		return x.xxx_hidden_RequestsPerMinute
	}
	return 0
}

func (x *RateLimit) GetBurst() uint32 {
	if x != nil {
		return x.xxx_hidden_Burst
	}
	return 0
}

func (x *RateLimit) SetRequestsPerMinute(v uint32) {
	x.xxx_hidden_RequestsPerMinute = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RateLimit) SetBurst(v uint32) {
	x.xxx_hidden_Burst = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RateLimit) HasRequestsPerMinute() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RateLimit) HasBurst() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RateLimit) ClearRequestsPerMinute() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RequestsPerMinute = 0
}

func (x *RateLimit) ClearBurst() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Burst = 0
}

type RateLimit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RequestsPerMinute *uint32
	Burst             *uint32
}

func (b0 RateLimit_builder) Build() *RateLimit {
	m0 := &RateLimit{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RequestsPerMinute != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_RequestsPerMinute = *b.RequestsPerMinute
	}
	if b.Burst != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Burst = *b.Burst
	}
	return m0
}

// ProviderInfo describes metadata about a provider service.
type ProviderInfo struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_RateLimit    *RateLimit             `protobuf:"bytes,2,opt,name=rate_limit,json=rateLimit"`
	xxx_hidden_Capabilities []string               `protobuf:"bytes,3,rep,name=capabilities"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_translator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ProviderInfo) GetRateLimit() *RateLimit {
	if x != nil {
		return x.xxx_hidden_RateLimit
	}
	return nil
}

func (x *ProviderInfo) GetCapabilities() []string {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return nil
}

func (x *ProviderInfo) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ProviderInfo) SetRateLimit(v *RateLimit) {
	x.xxx_hidden_RateLimit = v
}

func (x *ProviderInfo) SetCapabilities(v []string) {
	x.xxx_hidden_Capabilities = v
}

func (x *ProviderInfo) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProviderInfo) HasRateLimit() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RateLimit != nil
}

func (x *ProviderInfo) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *ProviderInfo) ClearRateLimit() {
	x.xxx_hidden_RateLimit = nil
}

type ProviderInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name         *string
	RateLimit    *RateLimit
	Capabilities []string
}

func (b0 ProviderInfo_builder) Build() *ProviderInfo {
	m0 := &ProviderInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_RateLimit = b.RateLimit
	x.xxx_hidden_Capabilities = b.Capabilities
	return m0
}

var File_translator_proto protoreflect.FileDescriptor

const file_translator_proto_rawDesc = "" +
	"\n" +
	"\x10translator.proto\x12\x16subtitle.translator.v1\x1a!google/protobuf/go_features.proto\x1a\fconfig.proto\"\xd5\x01\n" +
	"\x0fRequestMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12N\n" +
	"\aheaders\x18\x03 \x03(\v24.subtitle.translator.v1.RequestMetadata.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\x7f\n" +
	"\x10TranslateRequest\x12;\n" +
	"\x04meta\x18\x01 \x01(\v2'.subtitle.translator.v1.RequestMetadataR\x04meta\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"s\n" +
	"\x11TranslateResponse\x12'\n" +
	"\x0ftranslated_text\x18\x01 \x01(\tR\x0etranslatedText\x125\n" +
	"\x06errors\x18\x02 \x03(\v2\x1d.subtitle.translator.v1.ErrorR\x06errors\"\x12\n" +
	"\x10GetConfigRequest\"V\n" +
	"\x11GetConfigResponse\x12A\n" +
	"\x06config\x18\x01 \x01(\v2).subtitle.config.v1.SubtitleManagerConfigR\x06config\"U\n" +
	"\x10SetConfigRequest\x12A\n" +
	"\x06config\x18\x01 \x01(\v2).subtitle.config.v1.SubtitleManagerConfigR\x06config\"\x13\n" +
	"\x11SetConfigResponse\"Q\n" +
	"\tRateLimit\x12.\n" +
	"\x13requests_per_minute\x18\x01 \x01(\rR\x11requestsPerMinute\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\rR\x05burst\"\x88\x01\n" +
	"\fProviderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12@\n" +
	"\n" +
	"rate_limit\x18\x02 \x01(\v2!.subtitle.translator.v1.RateLimitR\trateLimit\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities2\xb9\x02\n" +
	"\x11TranslatorService\x12`\n" +
	"\tTranslate\x12(.subtitle.translator.v1.TranslateRequest\x1a).subtitle.translator.v1.TranslateResponse\x12`\n" +
	"\tGetConfig\x12(.subtitle.translator.v1.GetConfigRequest\x1a).subtitle.translator.v1.GetConfigResponse\x12`\n" +
	"\tSetConfig\x12(.subtitle.translator.v1.SetConfigRequest\x1a).subtitle.translator.v1.SetConfigResponseBJZ@github.com/jdfalk/subtitle-manager/pkg/translatorpb;translatorpb\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_translator_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_translator_proto_goTypes = []any{
	(*RequestMetadata)(nil),                // 0: subtitle.translator.v1.RequestMetadata
	(*Error)(nil),                          // 1: subtitle.translator.v1.Error
	(*TranslateRequest)(nil),               // 2: subtitle.translator.v1.TranslateRequest
	(*TranslateResponse)(nil),              // 3: subtitle.translator.v1.TranslateResponse
	(*GetConfigRequest)(nil),               // 4: subtitle.translator.v1.GetConfigRequest
	(*GetConfigResponse)(nil),              // 5: subtitle.translator.v1.GetConfigResponse
	(*SetConfigRequest)(nil),               // 6: subtitle.translator.v1.SetConfigRequest
	(*SetConfigResponse)(nil),              // 7: subtitle.translator.v1.SetConfigResponse
	(*RateLimit)(nil),                      // 8: subtitle.translator.v1.RateLimit
	(*ProviderInfo)(nil),                   // 9: subtitle.translator.v1.ProviderInfo
	nil,                                    // 10: subtitle.translator.v1.RequestMetadata.HeadersEntry
	(*configpb.SubtitleManagerConfig)(nil), // 11: subtitle.config.v1.SubtitleManagerConfig
}
var file_translator_proto_depIdxs = []int32{
	10, // 0: subtitle.translator.v1.RequestMetadata.headers:type_name -> subtitle.translator.v1.RequestMetadata.HeadersEntry
	0,  // 1: subtitle.translator.v1.TranslateRequest.meta:type_name -> subtitle.translator.v1.RequestMetadata
	1,  // 2: subtitle.translator.v1.TranslateResponse.errors:type_name -> subtitle.translator.v1.Error
	11, // 3: subtitle.translator.v1.GetConfigResponse.config:type_name -> subtitle.config.v1.SubtitleManagerConfig
	11, // 4: subtitle.translator.v1.SetConfigRequest.config:type_name -> subtitle.config.v1.SubtitleManagerConfig
	8,  // 5: subtitle.translator.v1.ProviderInfo.rate_limit:type_name -> subtitle.translator.v1.RateLimit
	2,  // 6: subtitle.translator.v1.TranslatorService.Translate:input_type -> subtitle.translator.v1.TranslateRequest
	4,  // 7: subtitle.translator.v1.TranslatorService.GetConfig:input_type -> subtitle.translator.v1.GetConfigRequest
	6,  // 8: subtitle.translator.v1.TranslatorService.SetConfig:input_type -> subtitle.translator.v1.SetConfigRequest
	3,  // 9: subtitle.translator.v1.TranslatorService.Translate:output_type -> subtitle.translator.v1.TranslateResponse
	5,  // 10: subtitle.translator.v1.TranslatorService.GetConfig:output_type -> subtitle.translator.v1.GetConfigResponse
	7,  // 11: subtitle.translator.v1.TranslatorService.SetConfig:output_type -> subtitle.translator.v1.SetConfigResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_translator_proto_init() }
func file_translator_proto_init() {
	if File_translator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translator_proto_rawDesc), len(file_translator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translator_proto_goTypes,
		DependencyIndexes: file_translator_proto_depIdxs,
		MessageInfos:      file_translator_proto_msgTypes,
	}.Build()
	File_translator_proto = out.File
	file_translator_proto_goTypes = nil
	file_translator_proto_depIdxs = nil
}
