# file: .github/workflows/copilot-tickets.yml
#
# DEPRECATED: This workflow has been superseded by unified-issue-management.yml
#
# This file is kept for reference but the functionality has been moved to
# the unified workflow which provides:
# - Enhanced error handling and logging
# - Unified codebase for all issue management operations
# - Better duplicate handling and event processing
# - Matrix-based parallel execution
# - Comprehensive summary generation
# - GUID-based tracking
#
# The unified workflow handles all Copilot review comment ticket management
# and integrates with other issue operations for better coordination.

name: Copilot Review Tickets (DEPRECATED)

on:
  # Disabled - functionality moved to unified-issue-management.yml
  workflow_dispatch:
    inputs:
      force_run:
        description: "Force run deprecated workflow (use unified-issue-management.yml instead)"
        required: false
        type: boolean
        default: false

jobs:
  deprecation-notice:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation Notice
        run: |
          echo "⚠️  DEPRECATION NOTICE"
          echo ""
          echo "This workflow has been superseded by unified-issue-management.yml"
          echo ""
          echo "Copilot review tickets are now handled automatically by:"
          echo "- unified-issue-management.yml (triggers on PR events)"
          echo ""
          echo "The unified workflow provides:"
          echo "- Better error handling and logging"
          echo "- Matrix-based parallel execution"
          echo "- Integration with other issue operations"
          echo "- GUID-based duplicate prevention"
          echo "- Comprehensive summary generation"

  legacy-copilot-tickets:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.force_run == 'true' }}
    permissions:
      issues: write
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Manage tickets (legacy)
        run: |
          echo "🔄 Running legacy copilot-tickets script"
          python .github/scripts/issue_manager.py copilot-tickets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
