# file: .github/workflows/docker-build.yml
name: "docker-build: Build and Push Docker Image for Subtitle Manager"

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read # Required for repository checkout
  packages: write # Required for pushing to container registry
  id-token: write # Required for signing and attestations
  attestations: write # Required for build attestations

jobs:
  build:
    uses: jdfalk/ghcommon/.github/workflows/reusable-docker-build.yml@main
    with:
      image-name: subtitle-manager
      registry: ghcr.io
      dockerfile: ./Dockerfile
      context: .
      platforms: linux/amd64,linux/arm64
      build-args: |
        # Add any additional build args here
      push: true
      generate-sbom: true
      generate-attestation: true
      scan-vulnerability: true
      tag-suffix: ""
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
