name: Frontend (Node.js) Tests

on:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "webui/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches: [main]
    paths:
      - "webui/**"
      - ".github/workflows/frontend.yml"

jobs:
  test:
    name: Node.js Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: webui

    strategy:
      matrix:
        node-version: [18, 20, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: webui/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run ESLint
        run: npm run lint --if-present

      - name: Run Prettier check
        run: npm run format:check --if-present

      - name: Run type checking
        run: npm run type-check --if-present

      - name: Run unit tests
        run: npm test --if-present

      - name: Run build
        run: npm run build

      - name: Check build output
        run: |
          echo "Build completed successfully"
          ls -la dist/
          du -sh dist/

      - name: Upload build artifacts
        if: matrix.node-version == '20' # Only upload from one Node version
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: webui/dist/
          retention-days: 7

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    defaults:
      run:
        working-directory: webui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: webui/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build application
        run: npm run build

      - name: Run Playwright tests
        run: npm run test:e2e --if-present

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: webui/playwright-report/
          retention-days: 30

  accessibility:
    name: Accessibility Tests
    runs-on: ubuntu-latest
    needs: test

    defaults:
      run:
        working-directory: webui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: webui/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build application
        run: npm run build

      - name: Run accessibility tests
        run: npm run test:a11y --if-present

      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: "./webui/lighthouserc.json"
          temporaryPublicStorage: true
          uploadArtifacts: true

  security:
    name: Security Audit
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: webui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: webui/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Run dependency vulnerability check
        run: npx audit-ci --moderate

  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    needs: test

    defaults:
      run:
        working-directory: webui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: webui/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build with bundle analysis
        run: npm run build

      - name: Analyze bundle size
        run: npm run analyze --if-present

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: webui/dist/
          retention-days: 7
