name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Format
        run: test -z "$(gofmt -s -l $(git ls-files '*.go'))"
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
