# file: .github/workflows/intelligent-labeling.yml
# version: 1.0.0
# guid: 4e5f6a7b-8c9d-0e1f-2a3b-4c5d6e7f8a9b

name: Intelligent Issue Labeling

on:
  issues:
    types: [opened, edited]
  schedule:
    - cron: "0 2 * * *"  # Daily at 2 AM UTC
  workflow_dispatch:
    inputs:
      batch_size:
        description: "Number of issues to process"
        required: false
        default: "10"
        type: string
      dry_run:
        description: "Run in dry-run mode (no changes)"
        required: false
        default: false
        type: boolean

jobs:
  intelligent-labeling:
    uses: jdfalk/ghcommon/.github/workflows/reusable-unified-automation.yml@main
    with:
      operation: "intelligent-labeling"
      il_enabled: true
      il_dry_run: ${{ inputs.dry_run || false }}
      il_batch_size: ${{ fromJSON(inputs.batch_size || '10') }}
      il_use_ai_fallback: true
      il_confidence_threshold: 0.7
      il_max_labels_per_issue: 8
      il_preserve_existing_labels: true
      il_label_config_path: ".github/intelligent-labeling.yml"
    secrets: inherit
