# file: .github/workflows/pr-labeler.yml
# version: 1.0.0
# guid: e5f6a7b8-c9d0-41e2-f3a4-b5c6d7e8f9a0

name: Pull Request Labeler

# Automatically label pull requests based on changed files and branch names
# Uses the reusable labeler workflow from ghcommon repository

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:
    inputs:
      pr_numbers:
        description: "Comma-separated list of PR numbers to reprocess (e.g., 123,456,789)"
        required: false
        type: string

jobs:
  labeler:
    uses: jdfalk/ghcommon/.github/workflows/reusable-labeler.yml@main
    permissions:
      contents: read
      pull-requests: write
      issues: write
    with:
      configuration-path: ".github/labeler.yml"
      sync-labels: true
      dot: true
      pr-numbers: ${{ github.event.inputs.pr_numbers || '' }}
    secrets:
      github-token: ${{ secrets.JF_CI_GH_PAT || secrets.GITHUB_TOKEN }}
