# file: .github/workflows/unified-automation.yml
# version: 2.0.0
# guid: 9a8b7c6d-5e4f-3a2b-1c0d-2e3f4a5b6c7d

name: Unified Issue & Docs Automation

on:
  workflow_dispatch:

jobs:
  orchestrate:
    uses: jdfalk/ghcommon/.github/workflows/reusable-unified-automation.yml@main
    with:
      operation: all
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
