name: Update Issues

# This workflow processes issue updates from issue_updates.json
#
# MIGRATION NOTICE: This workflow is being migrated to use the unified
# issue management script at .github/scripts/issue_manager.py
#
# The new unified workflow (unified-issue-management.yml) provides:
# - Enhanced error handling and logging
# - Unified codebase for all issue management operations
# - Support for CodeQL alert ticket generation
# - Better duplicate handling and GUID support
# - Consistent API usage patterns
#
# Both workflows will run in parallel during the migration period.

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update GitHub issues (using unified script)
        id: issues
        if: ${{ hashFiles('issue_updates.json') != '' }}
        run: |
          echo "Using new unified issue management script..."
          python .github/scripts/issue_manager.py update-issues
          echo "processed=1" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

      - name: Remove issue_updates.json
        if: steps.issues.outputs.processed == '1'
        run: rm issue_updates.json

      - name: Create pull request for cleanup
        if: steps.issues.outputs.processed == '1'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: issue-updates-${{ github.run_id }}
          commit-message: "Remove processed issue updates"
          title: "Remove processed issue updates"
          body: "Remove processed entries from issue_updates.json."
