name: Update Issues (DEPRECATED)

# DEPRECATED: This workflow has been superseded by unified-issue-management.yml
#
# This file is kept for reference but the functionality has been moved to
# the unified workflow which provides:
# - Enhanced error handling and logging
# - Unified codebase for all issue management operations
# - Support for new grouped JSON format with GUID tracking
# - Better duplicate handling and event processing
# - Matrix-based parallel execution
# - Comprehensive summary generation

on:
  # Disabled - functionality moved to unified-issue-management.yml
  workflow_dispatch:
    inputs:
      force_run:
        description: "Force run deprecated workflow (use unified-issue-management.yml instead)"
        required: false
        type: boolean
        default: false

jobs:
  deprecation-notice:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation Notice
        run: |
          echo "⚠️  DEPRECATION NOTICE"
          echo ""
          echo "This workflow has been superseded by unified-issue-management.yml"
          echo ""
          echo "The new unified workflow provides:"
          echo "- Support for new grouped JSON format"
          echo "- GUID-based duplicate prevention"
          echo "- Better error handling and logging"
          echo "- Matrix-based parallel execution"
          echo "- Integration with other issue operations"
          echo ""
          echo "Please use the unified workflow instead."

  legacy-update:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.force_run == 'true' }}
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Update GitHub issues (legacy)
        run: |
          echo "🔄 Running legacy update-issues script"
          python .github/scripts/issue_manager.py update-issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
