name: Update Issues

on:
  push:
    branches: [main]

jobs:
  update:
    if: ${{ hashFiles('issue_updates.txt') != '' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Update GitHub issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          while read -r num state; do
            [ -z "$num" ] && continue
            echo "Updating issue $num -> $state"
            curl -s -X PATCH \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${REPO}/issues/$num" \
              -d "{\"state\":\"$state\"}"
          done < issue_updates.txt
