// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTranscriber creates a new instance of MockTranscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranscriber {
	mock := &MockTranscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranscriber is an autogenerated mock type for the Transcriber type
type MockTranscriber struct {
	mock.Mock
}

type MockTranscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranscriber) EXPECT() *MockTranscriber_Expecter {
	return &MockTranscriber_Expecter{mock: &_m.Mock}
}

// Transcribe provides a mock function for the type MockTranscriber
func (_mock *MockTranscriber) Transcribe(path string, lang string, apiKey string) ([]byte, error) {
	ret := _mock.Called(path, lang, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Transcribe")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) ([]byte, error)); ok {
		return returnFunc(path, lang, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) []byte); ok {
		r0 = returnFunc(path, lang, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(path, lang, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranscriber_Transcribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transcribe'
type MockTranscriber_Transcribe_Call struct {
	*mock.Call
}

// Transcribe is a helper method to define mock.On call
//   - path string
//   - lang string
//   - apiKey string
func (_e *MockTranscriber_Expecter) Transcribe(path interface{}, lang interface{}, apiKey interface{}) *MockTranscriber_Transcribe_Call {
	return &MockTranscriber_Transcribe_Call{Call: _e.mock.On("Transcribe", path, lang, apiKey)}
}

func (_c *MockTranscriber_Transcribe_Call) Run(run func(path string, lang string, apiKey string)) *MockTranscriber_Transcribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTranscriber_Transcribe_Call) Return(bytes []byte, err error) *MockTranscriber_Transcribe_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTranscriber_Transcribe_Call) RunAndReturn(run func(path string, lang string, apiKey string) ([]byte, error)) *MockTranscriber_Transcribe_Call {
	_c.Call.Return(run)
	return _c
}
