// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Transcriber is an autogenerated mock type for the Transcriber type
type Transcriber struct {
	mock.Mock
}

type Transcriber_Expecter struct {
	mock *mock.Mock
}

func (_m *Transcriber) EXPECT() *Transcriber_Expecter {
	return &Transcriber_Expecter{mock: &_m.Mock}
}

// Transcribe provides a mock function with given fields: path, lang, apiKey
func (_m *Transcriber) Transcribe(path string, lang string, apiKey string) ([]byte, error) {
	ret := _m.Called(path, lang, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Transcribe")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]byte, error)); ok {
		return rf(path, lang, apiKey)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []byte); ok {
		r0 = rf(path, lang, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(path, lang, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transcriber_Transcribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transcribe'
type Transcriber_Transcribe_Call struct {
	*mock.Call
}

// Transcribe is a helper method to define mock.On call
//   - path string
//   - lang string
//   - apiKey string
func (_e *Transcriber_Expecter) Transcribe(path interface{}, lang interface{}, apiKey interface{}) *Transcriber_Transcribe_Call {
	return &Transcriber_Transcribe_Call{Call: _e.mock.On("Transcribe", path, lang, apiKey)}
}

func (_c *Transcriber_Transcribe_Call) Run(run func(path string, lang string, apiKey string)) *Transcriber_Transcribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Transcriber_Transcribe_Call) Return(_a0 []byte, _a1 error) *Transcriber_Transcribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Transcriber_Transcribe_Call) RunAndReturn(run func(string, string, string) ([]byte, error)) *Transcriber_Transcribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewTranscriber creates a new instance of Transcriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTranscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transcriber {
	mock := &Transcriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
